name: Family Tracker App
on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: "https://index.docker.io/v1/"
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t wolfejw86/family-tracker-app:${{github.sha}} .
      - run: docker push wolfejw86/family-tracker-app:${{github.sha}}
      - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/webapps-container-deploy@v1
        with:
          app-name: 'family-tracker'
          images: 'wolfejw86/family-tracker-app:${{github.sha}}'
      - name: Azure logout
        run: az logout
